---
title: "Data Analysis 3: Assignment 1"
author: "Shah Ali Gardezi"
date: "1/25/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
rm(list=ls())
library(gridExtra)
#####################
## Import libraries##
#####################
library(tidyverse)
library(lspline)
library(cowplot)
library(boot)
library(estimatr)
library(huxtable)
library(stargazer)
library(modelsummary)
library(kableExtra)
library(dplyr)
library(data.table)
library(fixest)
library(caret)
library(skimr)
library(grid)
library(glmnet)
library(gridExtra)
```

```{r, include= F}
###########################################
## Set data dir, load theme and functions##
###########################################

# Importing the data
data <- fread("https://osf.io/4ay9x/download")
```

```{r,include=FALSE, warning=FALSE}
################
# Data Munging #
################

# Number of Observation in each Occupation 
ob <- data[,.(Count=.N),by=occ2012]


# Filtering the data for the chosen occupation (Customer service representative)
dt <- data %>% filter(occ2012==5240)
dt <-  data.table(dt)

datasummary_skim(dt)

# Creating a new wage per hour variable w
dt <- dt[, w := earnwke/uhours]
dt <- dt[age >= 20]

# Filtering on uhours to work on full time employee (minimum 40 hours) (dropped obs = 620 obs)
dt <- dt[uhours >= 40]

# counting Number observation in each Education Level
# Filter: keeping bachelors and under (dropped 109 observation)
dt[,.(count=.N), by= grade92]
dt <- dt[grade92 <= 43 & grade92 >= 39]  

# Checking age greater than 20
dt[,.(count=.N), by= age]
dt <- dt[age >= 20] #14 obs gone

# Looking at a quick summary of some of the key variables
datasummary(w + grade92 + age ~ Mean + SD + Min + Max + P25 + P75 + N , data = dt)

# Finding missing values
to_filter <- sapply(dt, function(x) sum(is.na(x)))
to_filter[to_filter > 0]

# dropping the ethnic column since there are 919 NA observation in the column 
dt <- dt[, ethnic := NULL]

```

